pipeline {

    agent any 

    stages {

        stage('welcome'){
            steps{

                echo 'hello Rajat'
            }
        }

        stage('terraform'){

            steps{

                echo'terraform pipeline'
            }
        }


    }
}
